// advPron.js
// Набор из 100 распространённых греческих наречий и местоимений с переводом

export const advPron = [
  { greek: 'εγώ',            translation: 'я' },
  { greek: 'εσύ',            translation: 'ты' },
  { greek: 'αυτός',          translation: 'он' },
  { greek: 'αυτή',           translation: 'она' },
  { greek: 'αυτό',           translation: 'оно' },
  { greek: 'εμείς',          translation: 'мы' },
  { greek: 'εσείς',          translation: 'вы' },
  { greek: 'αυτοί',          translation: 'они (м)' },
  { greek: 'αυτές',          translation: 'они (ж)' },
  { greek: 'αυτά',           translation: 'они (ср)' },

  { greek: 'ποιος',          translation: 'кто?' },
  { greek: 'ποια',           translation: 'кто? (ж)' },
  { greek: 'ποιο',           translation: 'что?' },
  { greek: 'τι',             translation: 'что?' },
  { greek: 'κάποιος',        translation: 'кто-то' },
  { greek: 'κάποια',         translation: 'кто-то (ж)' },
  { greek: 'κάτι',           translation: 'что-то' },
  { greek: 'κανείς',         translation: 'никто' },
  { greek: 'τίποτα',         translation: 'ничего' },
  { greek: 'όλοι',           translation: 'все (м)' },

  { greek: 'όλες',           translation: 'все (ж)' },
  { greek: 'όλα',            translation: 'все (ср)' },
  { greek: 'που',            translation: 'который/где' },
  { greek: 'όπου',           translation: 'где' },
  { greek: 'μόνο',           translation: 'только' },
  { greek: 'μαζί',           translation: 'вместе' },
  { greek: 'εδώ',            translation: 'здесь' },
  { greek: 'εκεί',           translation: 'там' },
  { greek: 'παρακάτω',       translation: 'ниже' },
  { greek: 'πάνω',           translation: 'сверху' },

  { greek: 'κάτω',           translation: 'снизу' },
  { greek: 'μέσα',           translation: 'внутри' },
  { greek: 'έξω',            translation: 'снаружи' },
  { greek: 'μπροστά',        translation: 'впереди' },
  { greek: 'πίσω',           translation: 'позади' },
  { greek: 'δίπλα',          translation: 'рядом' },
  { greek: 'ανάμεσα',        translation: 'между' },
  { greek: 'τώρα',           translation: 'сейчас' },
  { greek: 'σήμερα',         translation: 'сегодня' },
  { greek: 'χθες',           translation: 'вчера' },

  { greek: 'αύριο',          translation: 'завтра' },
  { greek: 'μετά',           translation: 'потом' },
  { greek: 'πριν',           translation: 'до' },
  { greek: 'ξανά',           translation: 'снова' },
  { greek: 'ώρες',           translation: 'иногда' },
  { greek: 'μόλις',          translation: 'только что' },
  { greek: 'ήδη',            translation: 'уже' },
  { greek: 'ακόμα',          translation: 'еще' },
  { greek: 'πάντα',         translation: 'всегда' },
  { greek: 'ποτέ',          translation: 'никогда' },

  { greek: 'συχνά',          translation: 'часто' },
  { greek: 'σπάνια',        translation: 'редко' },
  { greek: 'συνήθως',       translation: 'обычно' },
  { greek: 'γρήγορα',       translation: 'быстро' },
  { greek: 'αργά',          translation: 'медленно' },
  { greek: 'καλά',          translation: 'хорошо' },
  { greek: 'άσχημα',        translation: 'плохо' },
  { greek: 'εύκολα',        translation: 'легко' },
  { greek: 'δύσκολα',       translation: 'трудно' },
  { greek: 'πολύ',          translation: 'очень' },

  { greek: 'λίγο',          translation: 'немного' },
  { greek: 'περισσότερο',   translation: 'больше' },
  { greek: 'λιγότερο',      translation: 'меньше' },
  { greek: 'σχεδόν',        translation: 'почти' },
  { greek: 'ίσως',          translation: 'возможно' },
  { greek: 'σίγουρα',       translation: 'точно' },
  { greek: 'απλά',          translation: 'просто' },
  { greek: 'τελικά',        translation: 'наконец' },
  { greek: 'άμεσα',         translation: 'сразу' },
  { greek: 'συνεχώς',       translation: 'непрерывно' },

  { greek: 'διαρκώς',       translation: 'постоянно' },
  { greek: 'σχετικά',       translation: 'относительно' },
  { greek: 'αρκετά',        translation: 'достаточно' },
  { greek: 'τελευταία',     translation: 'недавно' },
  { greek: 'οπουδήποτε',    translation: 'где-угодно' },
  { greek: 'παντού',        translation: 'везде' },
  { greek: 'πουθενά',       translation: 'нигде' },
  { greek: 'αλλού',         translation: 'в другом месте' },
  { greek: 'αλλιώς',        translation: 'иначе' },
  { greek: 'διαφορετικά',   translation: 'по-другому' },

  { greek: 'σωστά',         translation: 'правильно' },
  { greek: 'λάθος',         translation: 'неправильно' },
  { greek: 'θετικά',        translation: 'положительно' },
  { greek: 'αρνητικά',      translation: 'отрицательно' },
  { greek: 'ξεχωριστά',     translation: 'отдельно' },
  { greek: 'εσωτερικά',     translation: 'внутренне' },
  { greek: 'εξωτερικά',     translation: 'внешне' },
  { greek: 'υπερβολικά',    translation: 'чрезмерно' },
  { greek: 'φυσικά',        translation: 'естественно' },
  { greek: 'σίωπα',         translation: 'молчи (наречие)' }
];
