// nouns.js
// Список распространенных греческих существительных с переводом, родом и формой множественного числа

export const nouns = [
  { greek: 'άνθρωπος', translation: 'человек', gender: 'm', plural: 'άνθρωποι' },
  { greek: 'άντρας', translation: 'мужчина', gender: 'm', plural: 'άντρες' },
  { greek: 'γυναίκα', translation: 'женщина', gender: 'f', plural: 'γυναίκες' },
  { greek: 'παιδί', translation: 'ребенок', gender: 'n', plural: 'παιδιά' },
  { greek: 'σπίτι', translation: 'дом', gender: 'n', plural: 'σπίτια' },
  { greek: 'πόρτα', translation: 'дверь', gender: 'f', plural: 'πόρτες' },
  { greek: 'παράθυρο', translation: 'окно', gender: 'n', plural: 'παράθυρα' },
  { greek: 'τραπέζι', translation: 'стол', gender: 'n', plural: 'τραπέζια' },
  { greek: 'καρέκλα', translation: 'стул', gender: 'f', plural: 'καρέκλες' },
  { greek: 'κρεβάτι', translation: 'кровать', gender: 'n', plural: 'κρεβάτια' },
  { greek: 'νερό', translation: 'вода', gender: 'n', plural: 'νερά' },
  { greek: 'ψωμί', translation: 'хлеб', gender: 'n', plural: 'ψωμιά' },
  { greek: 'φαγητό', translation: 'еда', gender: 'n', plural: 'φαγητά' },
  { greek: 'φίλος', translation: 'друг', gender: 'm', plural: 'φίλοι' },
  { greek: 'φίλη', translation: 'подруга', gender: 'f', plural: 'φίλες' },
  { greek: 'οικογένεια', translation: 'семья', gender: 'f', plural: 'οικογένειες' },
  { greek: 'μητέρα', translation: 'мать', gender: 'f', plural: 'μητέρες' },
  { greek: 'πατέρας', translation: 'отец', gender: 'm', plural: 'πατέρες' },
  { greek: 'αδελφός', translation: 'брат', gender: 'm', plural: 'αδελφοί' },
  { greek: 'αδελφή', translation: 'сестра', gender: 'f', plural: 'αδελφές' },
  { greek: 'γιος', translation: 'сын', gender: 'm', plural: 'γιοι' },
  { greek: 'κόρη', translation: 'дочь', gender: 'f', plural: 'κόρες' },
  { greek: 'παππούς', translation: 'дедушка', gender: 'm', plural: 'παππούδες' },
  { greek: 'γιαγιά', translation: 'бабушка', gender: 'f', plural: 'γιαγιάδες' },
  { greek: 'χρόνος', translation: 'год, время', gender: 'm', plural: 'χρόνοι' }, // или χρόνια (для времени, лет)
  { greek: 'μέρα', translation: 'день', gender: 'f', plural: 'μέρες' },
  { greek: 'νύχτα', translation: 'ночь', gender: 'f', plural: 'νύχτες' },
  { greek: 'πρωί', translation: 'утро', gender: 'n', plural: 'πρωινά' },
  { greek: 'απόγευμα', translation: 'вечер (после полудня)', gender: 'n', plural: 'απογεύματα' },
  { greek: 'βράδυ', translation: 'вечер', gender: 'n', plural: 'βράδια' },
  { greek: 'εβδομάδα', translation: 'неделя', gender: 'f', plural: 'εβδομάδες' },
  { greek: 'μήνας', translation: 'месяц', gender: 'm', plural: 'μήνες' },
  { greek: 'ώρα', translation: 'час, время', gender: 'f', plural: 'ώρες' },
  { greek: 'λεπτό', translation: 'минута', gender: 'n', plural: 'λεπτά' },
  { greek: 'στιγμή', translation: 'момент, мгновение', gender: 'f', plural: 'στιγμές' },
  { greek: 'χώρα', translation: 'страна', gender: 'f', plural: 'χώρες' },
  { greek: 'πόλη', translation: 'город', gender: 'f', plural: 'πόλεις' },
  { greek: 'χωριό', translation: 'деревня', gender: 'n', plural: 'χωριά' },
  { greek: 'δρόμος', translation: 'дорога, улица', gender: 'm', plural: 'δρόμοι' },
  { greek: 'αυτοκίνητο', translation: 'машина', gender: 'n', plural: 'αυτοκίνητα' },
  { greek: 'βιβλίο', translation: 'книга', gender: 'n', plural: 'βιβλία' },
  { greek: 'μολύβι', translation: 'карандаш', gender: 'n', plural: 'μολύβια' },
  { greek: 'στυλό', translation: 'ручка', gender: 'n', plural: 'στυλό' }, // или στυλοί (m)
  { greek: 'τετράδιο', translation: 'тетрадь', gender: 'n', plural: 'τετράδια' },
  { greek: 'σχολείο', translation: 'школа', gender: 'n', plural: 'σχολεία' },
  { greek: 'δάσκαλος', translation: 'учитель', gender: 'm', plural: 'δάσκαλοι' },
  { greek: 'δασκάλα', translation: 'учительница', gender: 'f', plural: 'δασκάλες' },
  { greek: 'μαθητής', translation: 'ученик', gender: 'm', plural: 'μαθητές' },
  { greek: 'μαθήτρια', translation: 'ученица', gender: 'f', plural: 'μαθήτριες' },
  { greek: 'δουλειά', translation: 'работа', gender: 'f', plural: 'δουλειές' },
  { greek: 'γραφείο', translation: 'офис, письменный стол', gender: 'n', plural: 'γραφεία' },
  { greek: 'γιατρός', translation: 'врач', gender: 'm', plural: 'γιατροί' },
  { greek: 'νοσοκομείο', translation: 'больница', gender: 'n', plural: 'νοσοκομεία' },
  { greek: 'χρήμα', translation: 'деньги (ед.ч.)', gender: 'n', plural: 'χρήματα (мн.ч)' },
  { greek: 'κατάστημα', translation: 'магазин', gender: 'n', plural: 'καταστήματα' },
  { greek: 'αγορά', translation: 'рынок, покупка', gender: 'f', plural: 'αγορές' },
  { greek: 'ζωή', translation: 'жизнь', gender: 'f', plural: 'ζωές' },
  { greek: 'θάνατος', translation: 'смерть', gender: 'm', plural: 'θάνατοι' },
  { greek: 'αγάπη', translation: 'любовь', gender: 'f', plural: 'αγάπες' },
  { greek: 'χαρά', translation: 'радость', gender: 'f', plural: 'χαρές' },
  { greek: 'λύπη', translation: 'печаль', gender: 'f', plural: 'λύπες' },
  { greek: 'φόβος', translation: 'страх', gender: 'm', plural: 'φόβοι' },
  { greek: 'ελπίδα', translation: 'надежда', gender: 'f', plural: 'ελπίδες' },
  { greek: 'πρόβλημα', translation: 'проблема', gender: 'n', plural: 'προβλήματα' },
  { greek: 'λύση', translation: 'решение', gender: 'f', plural: 'λύσεις' },
  { greek: 'αρχή', translation: 'начало', gender: 'f', plural: 'αρχές' },
  { greek: 'τέλος', translation: 'конец', gender: 'n', plural: 'τέλη' },
  { greek: 'κεφάλι', translation: 'голова', gender: 'n', plural: 'κεφάλια' },
  { greek: 'χέρι', translation: 'рука (кисть)', gender: 'n', plural: 'χέρια' },
  { greek: 'πόδι', translation: 'нога (ступня)', gender: 'n', plural: 'πόδια' },
  { greek: 'μάτι', translation: 'глаз', gender: 'n', plural: 'μάτια' },
  { greek: 'αυτί', translation: 'ухо', gender: 'n', plural: 'αυτιά' },
  { greek: 'μύτη', translation: 'нос', gender: 'f', plural: 'μύτες' },
  { greek: 'στόμα', translation: 'рот', gender: 'n', plural: 'στόματα' },
  { greek: 'καρδιά', translation: 'сердце', gender: 'f', plural: 'καρδιές' },
  { greek: 'κόσμος', translation: 'мир, люди', gender: 'm', plural: 'κόσμοι' },
  { greek: 'ήλιος', translation: 'солнце', gender: 'm', plural: 'ήλιοι' },
  { greek: 'φεγγάρι', translation: 'луна, месяц', gender: 'n', plural: 'φεγγάρια' },
  { greek: 'αστέρι', translation: 'звезда', gender: 'n', plural: 'αστέρια' },
  { greek: 'ουρανός', translation: 'небо', gender: 'm', plural: 'ουρανοί' },
  { greek: 'γη', translation: 'земля', gender: 'f', plural: 'γες' }, // или γαίες
  { greek: 'θάλασσα', translation: 'море', gender: 'f', plural: 'θάλασσες' },
  { greek: 'βουνό', translation: 'гора', gender: 'n', plural: 'βουνά' },
  { greek: 'δέντρο', translation: 'дерево', gender: 'n', plural: 'δέντρα' },
  { greek: 'λουλούδι', translation: 'цветок', gender: 'n', plural: 'λουλούδια' },
  { greek: 'ζώο', translation: 'животное', gender: 'n', plural: 'ζώα' },
  { greek: 'σκύλος', translation: 'собака', gender: 'm', plural: 'σκύλοι' }, // или σκυλιά (n)
  { greek: 'γάτα', translation: 'кошка', gender: 'f', plural: 'γάτες' },
  { greek: 'πουλί', translation: 'птица', gender: 'n', plural: 'πουλιά' },
  { greek: 'ψάρι', translation: 'рыба', gender: 'n', plural: 'ψάρια' },
  { greek: 'φρούτο', translation: 'фрукт', gender: 'n', plural: 'φρούτα' },
  { greek: 'λαχανικό', translation: 'овощ', gender: 'n', plural: 'λαχανικά' },
  { greek: 'κρέας', translation: 'мясо', gender: 'n', plural: 'κρέατα' },
  { greek: 'γάλα', translation: 'молоко', gender: 'n', plural: 'γάλατα' },
  { greek: 'τυρί', translation: 'сыр', gender: 'n', plural: 'τυριά' },
  { greek: 'αυγό', translation: 'яйцо', gender: 'n', plural: 'αυγά' },
  { greek: 'λάδι', translation: 'масло (оливковое)', gender: 'n', plural: 'λάδια' },
  { greek: 'κρασί', translation: 'вино', gender: 'n', plural: 'κρασιά' },
  { greek: 'καφές', translation: 'кофе', gender: 'm', plural: 'καφέδες' },
  { greek: 'τσάι', translation: 'чай', gender: 'n', plural: 'τσάγια' },
  { greek: 'ζάχαρη', translation: 'сахар', gender: 'f', plural: 'ζάχαρες' }, // редко используется во мн.ч.
  { greek: 'αλάτι', translation: 'соль', gender: 'n', plural: 'αλάτια' },
  { greek: 'αέρας', translation: 'воздух, ветер', gender: 'm', plural: 'αέρες' },
  { greek: 'φωτιά', translation: 'огонь', gender: 'f', plural: 'φωτιές' },
  { greek: 'πέτρα', translation: 'камень', gender: 'f', plural: 'πέτρες' },
  { greek: 'νόμος', translation: 'закон', gender: 'm', plural: 'νόμοι' },
  { greek: 'κράτος', translation: 'государство', gender: 'n', plural: 'κράτη' },
  { greek: 'πόλεμος', translation: 'война', gender: 'm', plural: 'πόλεμοι' },
  { greek: 'ειρήνη', translation: 'мир (покой)', gender: 'f', plural: 'ειρήνες' }, // редко используется во мн.ч.
  { greek: 'ιδέα', translation: 'идея', gender: 'f', plural: 'ιδέες' },
  { greek: 'λόγος', translation: 'слово, причина, речь', gender: 'm', plural: 'λόγοι' },
  { greek: 'ερώτηση', translation: 'вопрос', gender: 'f', plural: 'ερωτήσεις' },
  { greek: 'απάντηση', translation: 'ответ', gender: 'f', plural: 'απαντήσεις' },
  { greek: 'παιχνίδι', translation: 'игра, игрушка', gender: 'n', plural: 'παιχνίδια' },
  { greek: 'τραγούδι', translation: 'песня', gender: 'n', plural: 'τραγούδια' },
  { greek: 'μουσική', translation: 'музыка', gender: 'f', plural: 'μουσικές' }, // редко используется во мн.ч.
  { greek: 'ταινία', translation: 'фильм', gender: 'f', plural: 'ταινίες' },
  { greek: 'θέατρο', translation: 'театр', gender: 'n', plural: 'θέατρα' },
  { greek: 'ταξίδι', translation: 'путешествие', gender: 'n', plural: 'ταξίδια' },
  { greek: 'αμάξι', translation: 'машина (разг.)', gender: 'n', plural: 'αμάξια' }, // синоним αυτοκίνητο
  { greek: 'λεωφορείο', translation: 'автобус', gender: 'n', plural: 'λεωφορεία' },
  { greek: 'τρένο', translation: 'поезд', gender: 'n', plural: 'τρένα' },
  { greek: 'αεροπλάνο', translation: 'самолет', gender: 'n', plural: 'αεροπλάνα' },
  { greek: 'πλοίο', translation: 'корабль', gender: 'n', plural: 'πλοία' },
  { greek: 'λιμάνι', translation: 'порт', gender: 'n', plural: 'λιμάνια' },
  { greek: 'σταθμός', translation: 'станция, вокзал', gender: 'm', plural: 'σταθμοί' },
  { greek: 'ξενοδοχείο', translation: 'гостиница', gender: 'n', plural: 'ξενοδοχεία' },
  { greek: 'εστιατόριο', translation: 'ресторан', gender: 'n', plural: 'εστιατόρια' },
  { greek: 'φούρνος', translation: 'пекарня, печь', gender: 'm', plural: 'φούρνοι' },
  { greek: 'φαρμακείο', translation: 'аптека', gender: 'n', plural: 'φαρμακεία' },
  { greek: 'εκκλησία', translation: 'церковь', gender: 'f', plural: 'εκκλησίες' },
  { greek: 'μάθημα', translation: 'урок, предмет', gender: 'n', plural: 'μαθήματα' },
  { greek: 'γλώσσα', translation: 'язык', gender: 'f', plural: 'γλώσσες' },
  { greek: 'γράμμα', translation: 'буква, письмо', gender: 'n', plural: 'γράμματα' },
  { greek: 'αριθμός', translation: 'число, номер', gender: 'm', plural: 'αριθμοί' },
  { greek: 'χρώμα', translation: 'цвет', gender: 'n', plural: 'χρώματα' },
  { greek: 'μέγεθος', translation: 'размер', gender: 'n', plural: 'μεγέθη' },
  { greek: 'σχήμα', translation: 'форма, фигура', gender: 'n', plural: 'σχήματα' },
  { greek: 'πράγμα', translation: 'вещь, дело', gender: 'n', plural: 'πράγματα' },
  { greek: 'μέρος', translation: 'место, часть', gender: 'n', plural: 'μέρη' },
  { greek: 'είδος', translation: 'вид, сорт', gender: 'n', plural: 'είδη' },
  { greek: 'τρόπος', translation: 'способ', gender: 'm', plural: 'τρόποι' },
  { greek: 'διαφορά', translation: 'разница', gender: 'f', plural: 'διαφορές' },
  { greek: 'αξία', translation: 'ценность, стоимость', gender: 'f', plural: 'αξίες' },
  { greek: 'ευκαιρία', translation: 'возможность, шанс', gender: 'f', plural: 'ευκαιρίες' },
  { greek: 'κίνδυνος', translation: 'опасность', gender: 'm', plural: 'κίνδυνοι' },
  { greek: 'αποτέλεσμα', translation: 'результат', gender: 'n', plural: 'αποτελέσματα' },
  { greek: 'λάθος', translation: 'ошибка', gender: 'n', plural: 'λάθη' },
  { greek: 'βοήθεια', translation: 'помощь', gender: 'f', plural: 'βοήθειες' }, // редко во мн.ч.
  { greek: 'ομάδα', translation: 'команда, группа', gender: 'f', plural: 'ομάδες' },
  { greek: 'πρόσωπο', translation: 'лицо, личность', gender: 'n', plural: 'πρόσωπα' },
  { greek: 'ιστορία', translation: 'история, рассказ', gender: 'f', plural: 'ιστορίες' },
  { greek: 'εφημερίδα', translation: 'газета', gender: 'f', plural: 'εφημερίδες' },
  { greek: 'περιοδικό', translation: 'журнал', gender: 'n', plural: 'περιοδικά' },
  { greek: 'ρούχο', translation: 'одежда (ед. предмет)', gender: 'n', plural: 'ρούχα' },
  { greek: 'παπούτσι', translation: 'обувь (ед. предмет)', gender: 'n', plural: 'παπούτσια' },
  { greek: 'καπέλο', translation: 'шляпа, шапка', gender: 'n', plural: 'καπέλα' },
  { greek: 'τσάντα', translation: 'сумка', gender: 'f', plural: 'τσάντες' },
  { greek: 'κλειδί', translation: 'ключ', gender: 'n', plural: 'κλειδιά' },
  { greek: 'τηλέφωνο', translation: 'телефон', gender: 'n', plural: 'τηλέφωνα' },
  { greek: 'υπολογιστής', translation: 'компьютер', gender: 'm', plural: 'υπολογιστές' },
  { greek: 'τηλεόραση', translation: 'телевизор', gender: 'f', plural: 'τηλεοράσεις' },
  { greek: 'φως', translation: 'свет', gender: 'n', plural: 'φώτα' },
  { greek: 'καλοκαίρι', translation: 'лето', gender: 'n', plural: 'καλοκαίρια' },
  { greek: 'χειμώνας', translation: 'зима', gender: 'm', plural: 'χειμώνες' },
  { greek: 'άνοιξη', translation: 'весна', gender: 'f', plural: 'άνοιξεις' },
  { greek: 'φθινόπωρο', translation: 'осень', gender: 'n', plural: 'φθινόπωρα' },
  { greek: 'καιρός', translation: 'погода, время', gender: 'm', plural: 'καιροί' },
  { greek: 'πρωτεύουσα', translation: 'столица', gender: 'f', plural: 'πρωτεύουσες' },
  { greek: 'κέντρο', translation: 'центр', gender: 'n', plural: 'κέντρα' },
  { greek: 'αρχιτέκτονας', translation: 'архитектор', gender: 'm', plural: 'αρχιτέκτονες' },
  { greek: 'μηχανικός', translation: 'инженер, механик', gender: 'm', plural: 'μηχανικοί' },
  { greek: 'δικηγόρος', translation: 'адвокат', gender: 'm', plural: 'δικηγόροι' },
  { greek: 'καλλιτέχνης', translation: 'художник, артист', gender: 'm', plural: 'καλλιτέχνες' },
  { greek: 'συγγραφέας', translation: 'писатель', gender: 'm', plural: 'συγγραφείς' },
  { greek: 'αθλητής', translation: 'спортсмен', gender: 'm', plural: 'αθλητές' },
  { greek: 'πρόεδρος', translation: 'президент, председатель', gender: 'm', plural: 'πρόεδροι' },
  { greek: 'κυβέρνηση', translation: 'правительство', gender: 'f', plural: 'κυβερνήσεις' },
  { greek: 'νόημα', translation: 'смысл, значение', gender: 'n', plural: 'νοήματα' },
  { greek: 'αίσθημα', translation: 'чувство', gender: 'n', plural: 'αισθήματα' },
  { greek: 'όνειρο', translation: 'сон, мечта', gender: 'n', plural: 'όνειρα' },
  { greek: 'στόχος', translation: 'цель', gender: 'm', plural: 'στόχοι' },
  { greek: 'αλλαγή', translation: 'изменение, перемена', gender: 'f', plural: 'αλλαγές' },
  { greek: 'επιτυχία', translation: 'успех', gender: 'f', plural: 'επιτυχίες' },
  { greek: 'αποτυχία', translation: 'неудача', gender: 'f', plural: 'αποτυχίες' },
  { greek: 'παράδειγμα', translation: 'пример', gender: 'n', plural: 'παραδείγματα' },
  { greek: 'κανόνας', translation: 'правило', gender: 'm', plural: 'κανόνες' },
  { greek: 'απόφαση', translation: 'решение (принятое)', gender: 'f', plural: 'αποφάσεις' },
  { greek: 'σκέψη', translation: 'мысль', gender: 'f', plural: 'σκέψεις' },
];

// Примечание: Род и формы множественного числа могут иногда варьироваться или иметь особенности.
// Этот список представляет наиболее общие и стандартные формы.
// Некоторые существительные редко используются во множественном числе (например, абстрактные понятия).
// Для некоторых слов могут существовать синонимы или диалектные варианты.