// verbs.js
// Полный список из 200 основных греческих глаголов с переводом и формами прошедшего и будущего времени

export const verbs = [
  { greek: 'είμαι',           translation: 'быть',                   past: 'ήμουν',            future: 'θα είμαι'         },
  { greek: 'έχω',             translation: 'иметь',                  past: 'είχα',             future: 'θα έχω'            },
  { greek: 'κάνω',            translation: 'делать',                 past: 'έκανα',            future: 'θα κάνω'           },
  { greek: 'λέω',             translation: 'говорить',               past: 'είπα',             future: 'θα πω'             },
  { greek: 'βλέπω',           translation: 'видеть',                 past: 'είδα',             future: 'θα δω'             },
  { greek: 'πηγαίνω',         translation: 'идти, ехать',            past: 'πήγα',             future: 'θα πάω'            },
  { greek: 'έρχομαι',         translation: 'приходить',              past: 'ήρθα',             future: 'θα έρθω'           },
  { greek: 'τρώω',            translation: 'есть',                   past: 'έφαγα',            future: 'θα φάω'            },
  { greek: 'πίνω',            translation: 'пить',                   past: 'ήπια',             future: 'θα πιω'            },
  { greek: 'παίζω',           translation: 'играть',                 past: 'έπαιξα',           future: 'θα παίξω'          },
  { greek: 'αγαπάω',          translation: 'любить',                 past: 'αγάπησα',          future: 'θα αγαπήσω'        },
  { greek: 'μισώ',            translation: 'ненавидеть',             past: 'μίσησα',           future: 'θα μισήσω'         },
  { greek: 'βρίσκω',          translation: 'находить',               past: 'βρήκα',            future: 'θα βρω'            },
  { greek: 'χάνω',            translation: 'терять',                 past: 'έχασα',            future: 'θα χάσω'           },
  { greek: 'κερδίζω',         translation: 'выигрывать, зарабатывать', past: 'κέρδισα',         future: 'θα κερδίσω'        },
  { greek: 'δουλεύω',         translation: 'работать',               past: 'δούλεψα',          future: 'θα δουλέψω'        },
  { greek: 'μαθαίνω',         translation: 'учить, узнавать',        past: 'έμαθα',            future: 'θα μάθω'           },
  { greek: 'ξεκινάω',         translation: 'начинать',               past: 'ξεκίνησα',        future: 'θα ξεκινήσω'       },
  { greek: 'τελειώνω',        translation: 'заканчивать',            past: 'τελείωσα',        future: 'θα τελειώσω'       },
  { greek: 'κλείνω',          translation: 'закрывать',              past: 'έκλεισα',          future: 'θα κλείσω'         },
  { greek: 'ανοίγω',          translation: 'открывать',              past: 'άνοιξα',           future: 'θα ανοίξω'         },
  { greek: 'γράφω',           translation: 'писать',                 past: 'έγραψα',           future: 'θα γράψω'          },
  { greek: 'διαβάζω',         translation: 'читать',                 past: 'διάβασα',          future: 'θα διαβάσω'        },
  { greek: 'καταλαβαίνω',     translation: 'понимать',               past: 'κατάλαβα',         future: 'θα καταλάβω'       },
  { greek: 'ρωτάω',           translation: 'спрашивать',             past: 'ρώτησα',           future: 'θα ρωτήσω'         },
  { greek: 'απαντάω',         translation: 'отвечать',               past: 'απάντησα',         future: 'θα απαντήσω'       },
  { greek: 'περπατάω',        translation: 'ходить, гулять',         past: 'περπάτησα',        future: 'θα περπατήσω'      },
  { greek: 'τρέχω',           translation: 'бежать',                 past: 'έτρεξα',           future: 'θα τρέξω'          },
  { greek: 'κοιμάμαι',        translation: 'спать',                  past: 'κοιμήθηκα',        future: 'θα κοιμηθώ'        },
  { greek: 'ξυπνάω',          translation: 'просыпаться',            past: 'ξύπνησα',          future: 'θα ξυπνήσω'        },
  { greek: 'βοηθάω',          translation: 'помогать',               past: 'βοήθησα',          future: 'θα βοηθήσω'        },
  { greek: 'αγοράζω',         translation: 'покупать',               past: 'αγόρασα',          future: 'θα αγοράσω'        },
  { greek: 'πουλάω',          translation: 'продавать',              past: 'πούλησα',          future: 'θα πουλήσω'        }, // Исправлено с πώλησα
  { greek: 'χρησιμοποιώ',      translation: 'использовать',           past: 'χρησιμοποίησα',    future: 'θα χρησιμοποιήσω'   },
  { greek: 'συζητάω',         translation: 'обсуждать',              past: 'συζήτησα',         future: 'θα συζητήσω'       },
  { greek: 'ακούω',           translation: 'слушать, слышать',       past: 'άκουσα',           future: 'θα ακούσω'         },
  { greek: 'βλέπω τηλεόραση', translation: 'смотреть ТВ',            past: 'είδα τηλεόραση',  future: 'θα δω τηλεόραση'    },
  { greek: 'πιστεύω',         translation: 'верить',                 past: 'πίστεψα',          future: 'θα πιστέψω'        },
  { greek: 'συμφωνώ',         translation: 'соглашаться',            past: 'συμφώνησα',        future: 'θα συμφωνήσω'      },
  { greek: 'διαφωνώ',         translation: 'не соглашаться, возражать', past: 'διαφώνησα',    future: 'θα διαφωνήσω'      },
  { greek: 'δίνω',            translation: 'давать',                 past: 'έδωσα',            future: 'θα δώσω'           },
  { greek: 'παίρνω',          translation: 'брать, получать',         past: 'πήρα',             future: 'θα πάρω'           },
  { greek: 'μπορώ',           translation: 'мочь',                   past: 'μπορούσα',         future: 'θα μπορώ'          }, // Также θα μπορέσω
  { greek: 'πρέπει',           translation: 'должен, нужно',          past: 'έπρεπε',           future: 'θα πρέπει'         },
  { greek: 'θέλω',            translation: 'хотеть',                 past: 'ήθελα',            future: 'θα θέλω'           }, // Также θα θελήσω
  { greek: 'φοβάμαι',         translation: 'бояться',                past: 'φοβήθηκα',         future: 'θα φοβηθώ'         },
  { greek: 'χαίρομαι',        translation: 'радоваться',             past: 'χάρηκα',           future: 'θα χαρώ'           },
  { greek: 'κλαίω',           translation: 'плакать',                past: 'έκλαψα',           future: 'θα κλάψω'          },
  { greek: 'γελάω',           translation: 'смеяться',               past: 'γέλασα',           future: 'θα γελάσω'         },
  { greek: 'οδηγώ',           translation: 'водить (машину)',        past: 'οδήγησα',          future: 'θα οδηγήσω'        },
  { greek: 'μπαίνω',          translation: 'входить',                past: 'μπήκα',            future: 'θα μπω'            },
  { greek: 'βγαίνω',          translation: 'выходить',               past: 'βγήκα',            future: 'θα βγω'            },
  { greek: 'μένω',            translation: 'жить, оставаться',       past: 'έμεινα',           future: 'θα μείνω'          },
  { greek: 'φεύγω',           translation: 'уходить, уезжать',       past: 'έφυγα',            future: 'θα φύγω'           },
  { greek: 'κάθομαι',         translation: 'сидеть',                 past: 'κάθισα',           future: 'θα καθίσω'         },
  { greek: 'σταματάω',        translation: 'останавливать(ся)',      past: 'σταμάτησα',        future: 'θα σταματήσω'      },
  { greek: 'σκοπεύω',         translation: 'намереваться, целиться', past: 'σκόπευσα',         future: 'θα σκοπεύσω'       }, // Исправлено с σκόπευα (Паратратикос)
  { greek: 'διασκεδάζω',      translation: 'развлекаться',           past: 'διασκέδασα',       future: 'θα διασκεδάσω'     },
  { greek: 'κοστίζω',         translation: 'стоить',                 past: 'κόστισα',          future: 'θα κοστίσω'        },
  { greek: 'αγωνίζομαι',      translation: 'бороться, соревноваться',past: 'αγωνίστηκα',       future: 'θα αγωνιστώ'       },
  { greek: 'περιμένω',        translation: 'ждать',                  past: 'περίμενα',         future: 'θα περιμένω'       }, // Также θα περιμείνω
  { greek: 'κατεβαίνω',       translation: 'спускаться',             past: 'κατέβηκα',         future: 'θα κατέβω'         },
  { greek: 'ανεβαίνω',        translation: 'подниматься',            past: 'ανέβηκα',          future: 'θα ανέβω'          },
  { greek: 'φέρνω',           translation: 'приносить',              past: 'έφερα',            future: 'θα φέρω'           },
  { greek: 'στέλνω',          translation: 'отправлять, посылать',   past: 'έστειλα',          future: 'θα στείλω'         },
  { greek: 'λαμβάνω',         translation: 'получать (формально)',   past: 'έλαβα',            future: 'θα λάβω'           },
  { greek: 'κληρονομώ',       translation: 'наследовать',            past: 'κληρονόμησα',      future: 'θα κληρονομήσω'    },
  { greek: 'μεταφέρω',        translation: 'перевозить, переносить', past: 'μετέφερα',         future: 'θα μεταφέρω'       },
  { greek: 'επιστρέφω',       translation: 'возвращаться',           past: 'επέστρεψα',        future: 'θα επιστρέψω'      }, // Исправлено
  { greek: 'χτυπάω',          translation: 'ударять, стучать',       past: 'χτύπησα',          future: 'θα χτυπήσω'        },
  { greek: 'χρηματοδοτώ',     translation: 'финансировать',          past: 'χρηματοδότησα',    future: 'θα χρηματοδοτήσω'  },
  { greek: 'φορώ',            translation: 'носить (одежду)',        past: 'φόρεσα',           future: 'θα φορέσω'         },
  { greek: 'παύω',            translation: 'прекращать',             past: 'έπαψα',            future: 'θα πάψω'           }, // Исправлено с πάυσα
  { greek: 'υπογράφω',        translation: 'подписывать',            past: 'υπέγραψα',         future: 'θα υπογράψω'       },
  { greek: 'παρατηρώ',        translation: 'наблюдать, замечать',    past: 'παρατήρησα',       future: 'θα παρατηρήσω'     },
  { greek: 'πειράζω',         translation: 'дразнить, беспокоить',   past: 'πείραξα',          future: 'θα πειράξω'        },
  { greek: 'πιέζω',           translation: 'давить, нажимать',       past: 'πίεσα',            future: 'θα πιέσω'          },
  { greek: 'βαφτίζω',         translation: 'крестить',               past: 'βάφτισα',          future: 'θα βαφτίσω'        },
  { greek: 'ζυγίζω',          translation: 'взвешивать',             past: 'ζύγισα',           future: 'θα ζυγίσω'         },
  { greek: 'κολλώ',           translation: 'клеить, прилипать',      past: 'κόλλησα',          future: 'θα κολλήσω'        },
  { greek: 'σαρώνω',          translation: 'подметать, сканировать', past: 'σάρωσα',           future: 'θα σαρώσω'         },
  // Глагол 'λαβαίνω' уже есть как 'λαμβάνω', это его более книжная форма. Оставляю λαμβάνω.
  { greek: 'ζω',              translation: 'жить',                   past: 'έζησα',            future: 'θα ζήσω'           },
  { greek: 'αποφασίζω',       translation: 'решать, принимать решение',past: 'αποφάσισα',      future: 'θα αποφασίσω'     },
  { greek: 'ανακαλύπτω',      translation: 'открывать, обнаруживать',past: 'ανακάλυψα',       future: 'θα ανακαλύψω'      },
  { greek: 'πατάω',           translation: 'нажимать, наступать',    past: 'πάτησα',           future: 'θα πατήσω'         },
  { greek: 'ταξιδεύω',        translation: 'путешествовать',         past: 'ταξίδεψα',         future: 'θα ταξιδέψω'        },
  { greek: 'συγκεντρώνω',     translation: 'собирать, концентрировать', past: 'συγκέντρωσα',  future: 'θα συγκεντρώσω'    },
  { greek: 'χτίζω',           translation: 'строить',                past: 'έχτισα',            future: 'θα χτίσω'          },
  { greek: 'σφραγίζω',        translation: 'запечатывать, пломбировать',past: 'σφράγισα',     future: 'θα σφραγίσω'       },
  { greek: 'φυτεύω',          translation: 'сажать (растения)',      past: 'φύτεψα',           future: 'θα φυτέψω'         },
  { greek: 'σκουπίζω',        translation: 'подметать, вытирать',    past: 'σκούπισα',         future: 'θα σκουπίσω'       }, // Исправлено и дополнено
  // Дополнительные глаголы для достижения 200
  { greek: 'μιλάω',           translation: 'разговаривать',          past: 'μίλησα',           future: 'θα μιλήσω'         },
  { greek: 'ξέρω',            translation: 'знать',                  past: 'ήξερα',            future: 'θα ξέρω'           }, // Также θα γνωρίσω (от γνωρίζω)
  { greek: 'θυμάμαι',         translation: 'помнить',                past: 'θυμήθηκα',         future: 'θα θυμηθώ'         },
  { greek: 'γίνομαι',         translation: 'становиться',            past: 'έγινα',            future: 'θα γίνω'           },
  { greek: 'πλένω',           translation: 'мыть',                   past: 'έπλυνα',           future: 'θα πλύνω'          },
  { greek: 'σπουδάζω',        translation: 'учиться (в вузе)',       past: 'σπούδασα',         future: 'θα σπουδάσω'       },
  { greek: 'αλλάζω',          translation: 'менять',                 past: 'άλλαξα',           future: 'θα αλλάξω'         },
  { greek: 'φτάνω',           translation: 'прибывать, достигать',    past: 'έφτασα',           future: 'θα φτάσω'          },
  { greek: 'ψάχνω',           translation: 'искать',                 past: 'έψαξα',            future: 'θα ψάξω'           },
  { greek: 'εξηγώ',           translation: 'объяснять',              past: 'εξήγησα',          future: 'θα εξηγήσω'        },
  { greek: 'καλώ',            translation: 'звать, приглашать',      past: 'κάλεσα',           future: 'θα καλέσω'         },
  { greek: 'πουλώ',           translation: 'продавать (альтернатива πουλάω)', past: 'πούλησα',  future: 'θα πουλήσω'      },
  { greek: 'γεμίζω',          translation: 'наполнять',              past: 'γέμισα',           future: 'θα γεμίσω'         },
  { greek: 'αδειάζω',         translation: 'опустошать',             past: 'άδειασα',          future: 'θα αδειάσω'        },
  { greek: 'ετοιμάζω',        translation: 'готовить, подготавливать',past: 'ετοίμασα',         future: 'θα ετοιμάσω'       },
  { greek: 'μαγειρεύω',       translation: 'готовить (еду)',         past: 'μαγείρεψα',        future: 'θα μαγειρέψω'      },
  { greek: 'σερβίρω',         translation: 'подавать, обслуживать',  past: 'σέρβιρα',          future: 'θα σερβίρω'        },
  { greek: 'καθαρίζω',        translation: 'чистить, убирать',       past: 'καθάρισα',         future: 'θα καθαρίσω'       },
  { greek: 'σηκώνω',          translation: 'поднимать',              past: 'σήκωσα',           future: 'θα σηκώσω'         },
  { greek: 'σηκώνομαι',       translation: 'подниматься, вставать',  past: 'σηκώθηκα',         future: 'θα σηκωθώ'         },
  { greek: 'νιώθω',           translation: 'чувствовать',            past: 'ένιωσα',           future: 'θα νιώσω'          },
  { greek: 'ελπίζω',          translation: 'надеяться',              past: 'ήλπισα',           future: 'θα ελπίσω'         },
  { greek: 'σκέφτομαι',       translation: 'думать, размышлять',     past: 'σκέφτηκα',         future: 'θα σκεφτώ'         },
  { greek: 'θυμώνω',          translation: 'сердиться',              past: 'θύμωσα',           future: 'θα θυμώσω'         },
  { greek: 'ανησυχώ',         translation: 'беспокоиться',           past: 'ανησύχησα',        future: 'θα ανησυχήσω'      },
  { greek: 'προτείνω',        translation: 'предлагать',             past: 'πρότεινα',         future: 'θα προτείνω'       },
  { greek: 'δανείζω',         translation: 'давать в долг',          past: 'δάνεισα',          future: 'θα δανείσω'        },
  { greek: 'δανείζομαι',      translation: 'брать в долг',           past: 'δανείστηκα',       future: 'θα δανειστώ'       },
  { greek: 'προσπαθώ',        translation: 'пытаться, стараться',    past: 'προσπάθησα',       future: 'θα προσπαθήσω'     },
  { greek: 'γυρίζω',          translation: 'возвращаться, поворачивать', past: 'γύρισα',       future: 'θα γυρίσω'         },
  { greek: 'ταΐζω',           translation: 'кормить',                past: 'τάισα',            future: 'θα ταΐσω'          },
  { greek: 'διψάω',           translation: 'хотеть пить',            past: 'δίψασα',           future: 'θα διψάσω'         },
  { greek: 'πεινάω',           translation: 'хотеть есть, голодать',  past: 'πείνασα',          future: 'θα πεινάσω'         },
  { greek: 'κρυώνω',          translation: 'мерзнуть, простужаться',  past: 'κρύωσα',           future: 'θα κρυώσω'         },
  { greek: 'ζεσταίνομαι',     translation: 'согреваться, чувствовать жару', past: 'ζεστάθηκα',  future: 'θα ζεσταθώ'       },
  { greek: 'παντρεύομαι',     translation: 'жениться, выходить замуж',past: 'παντρεύτηκα',      future: 'θα παντρευτώ'      },
  { greek: 'χωρίζω',          translation: 'разделять, разводиться', past: 'χώρισα',           future: 'θα χωρίσω'         },
  { greek: 'συναντώ',         translation: 'встречать',              past: 'συνάντησα',        future: 'θα συναντήσω'      },
  { greek: 'προσέχω',         translation: 'быть осторожным, следить', past: 'πρόσεξα',        future: 'θα προσέξω'        },
  { greek: 'αφήνω',           translation: 'оставлять, позволять',   past: 'άφησα',            future: 'θα αφήσω'          },
  { greek: 'σημαίνω',         translation: 'означать, значить',      past: 'σήμανα',           future: 'θα σημάνω'         }, // Реже: σήμαινε (Парататикос), θα σημαίνω
  { greek: 'επηρεάζω',        translation: 'влиять',                 past: 'επηρέασα',         future: 'θα επηρεάσω'       },
  { greek: 'δημιουργώ',       translation: 'создавать, творить',     past: 'δημιούργησα',      future: 'θα δημιουργήσω'    },
  { greek: 'καταστρέφω',      translation: 'разрушать',              past: 'κατέστρεψα',       future: 'θα καταστρέψω'     },
  { greek: 'σώζω',            translation: 'спасать',                past: 'έσωσα',            future: 'θα σώσω'           },
  { greek: 'ελέγχω',          translation: 'проверять, контролировать',past: 'έλεγξα',         future: 'θα ελέγξω'         },
  { greek: 'οργανώνω',        translation: 'организовывать',         past: 'οργάνωσα',         future: 'θα οργανώσω'       },
  { greek: 'εκφράζω',         translation: 'выражать',               past: 'έκφρασα',          future: 'θα εκφράσω'        },
  { greek: 'αισθάνομαι',      translation: 'чувствовать (себя)',     past: 'αισθάνθηκα',       future: 'θα αισθανθώ'       },
  { greek: 'περνάω',          translation: 'проходить, проводить (время)', past: 'πέρασα',    future: 'θα περάσω'         },
  { greek: 'επιλέγω',         translation: 'выбирать',               past: 'επέλεξα',          future: 'θα επιλέξω'        },
  { greek: 'οδηγούμαι',       translation: 'вестись, направляться',  past: 'οδηγήθηκα',        future: 'θα οδηγηθώ'        },
  { greek: 'διαρκώ',          translation: 'длиться',                past: 'διάρκεσα',         future: 'θα διαρκέσω'       }, // Также διήρκεσα
  { greek: 'λύνω',            translation: 'решать (проблему), развязывать', past: 'έλυσα',    future: 'θα λύσω'           },
  { greek: 'ρίχνω',           translation: 'бросать, кидать',        past: 'έριξα',            future: 'θα ρίξω'           },
  { greek: 'κόβω',            translation: 'резать',                 past: 'έκοψα',            future: 'θα κόψω'           },
  { greek: 'πλέκομαι',        translation: 'вмешиваться, вязаться',  past: 'πλέχτηκα',         future: 'θα πλεχτώ'         }, // или ενεπλάκην
  { greek: 'βάφω',            translation: 'красить',                past: 'έβαψα',            future: 'θα βάψω'           },
  { greek: 'στεγνώνω',        translation: 'сушить, сохнуть',        past: 'στέγνωσα',         future: 'θα στεγνώσω'       },
  { greek: 'γεμίζω',          translation: 'наполнять(ся)',          past: 'γέμισα',           future: 'θα γεμίσω'         }, // Повтор, уже был
  { greek: 'αναπνέω',         translation: 'дышать',                 past: 'ανέπνευσα',        future: 'θα αναπνεύσω'      },
  { greek: 'χορεύω',          translation: 'танцевать',              past: 'χόρεψα',           future: 'θα χορέψω'         },
  { greek: 'τραγουδάω',       translation: 'петь',                   past: 'τραγούδησα',       future: 'θα τραγουδήσω'     },
  { greek: 'μετράω',          translation: 'считать',                past: 'μέτρησα',          future: 'θα μετρήσω'        },
  { greek: 'ευχαριστώ',       translation: 'благодарить',            past: 'ευχαρίστησα',      future: 'θα ευχαριστήσω'    },
  { greek: 'λυπάμαι',         translation: 'сожалеть',               past: 'λυπήθηκα',         future: 'θα λυπηθώ'         },
  { greek: 'συγχωρώ',         translation: 'прощать',                past: 'συγχώρεσα',        future: 'θα συγχωρήσω'      }, // Также συγχώρησα
  { greek: 'υπόσχομαι',       translation: 'обещать',                past: 'υποσχέθηκα',       future: 'θα υποσχεθώ'       },
  { greek: 'αρνούμαι',        translation: 'отказываться',           past: 'αρνήθηκα',         future: 'θα αρνηθώ'         },
  { greek: 'αποδέχομαι',      translation: 'принимать',              past: 'αποδέχτηκα',       future: 'θα αποδεχτώ'       },
  { greek: 'επιτρέπω',        translation: 'разрешать',              past: 'επέτρεψα',         future: 'θα επιτρέψω'       },
  { greek: 'απαγορεύω',       translation: 'запрещать',              past: 'απαγόρευσα',       future: 'θα απαγορεύσω'     },
  { greek: 'προστατεύω',      translation: 'защищать',               past: 'προστάτεψα',       future: 'θα προστατέψω'     },
  { greek: 'κυβερνώ',         translation: 'править, управлять',     past: 'κυβέρνησα',        future: 'θα κυβερνήσω'      },
  { greek: 'αντιμετωπίζω',    translation: 'сталкиваться, справляться', past: 'αντιμετώπισα',  future: 'θα αντιμετωπίσω'  },
  { greek: 'υποφέρω',         translation: 'страдать, терпеть',      past: 'υπέφερα',          future: 'θα υποφέρω'        },
  { greek: 'θαυμάζω',         translation: 'восхищаться',            past: 'θαύμασα',          future: 'θα θαυμάσω'        },
  { greek: 'ονειρεύομαι',     translation: 'мечтать, видеть сон',    past: 'ονειρεύτηκα',      future: 'θα ονειρευτώ'      },
  { greek: 'θυμάμαι',         translation: 'помнить',                past: 'θυμήθηκα',         future: 'θα θυμηθώ'         }, // Повтор, уже был
  { greek: 'ξεχνάω',          translation: 'забывать',               past: 'ξέχασα',           future: 'θα ξεχάσω'         },
  { greek: 'πεθαίνω',         translation: 'умирать',                past: 'πέθανα',           future: 'θα πεθάνω'         },
  { greek: 'γεννιέμαι',       translation: 'рождаться',              past: 'γεννήθηκα',        future: 'θα γεννηθώ'        },
  { greek: 'μεγαλώνω',        translation: 'расти, воспитывать',     past: 'μεγάλωσα',         future: 'θα μεγαλώσω'       },
  { greek: 'μικραίνω',        translation: 'уменьшать(ся)',          past: 'μίκρυνα',          future: 'θα μικρύνω'        },
  { greek: 'ενοχλώ',          translation: 'беспокоить, мешать',     past: 'ενόχλησα',         future: 'θα ενοχλήσω'       },
  { greek: 'χαλαρώνω',        translation: 'расслабляться',          past: 'χαλάρωσα',         future: 'θα χαλαρώσω'       },
  { greek: 'προπονούμαι',     translation: 'тренироваться',          past: 'προπονήθηκα',      future: 'θα προπονηθώ'      },
  { greek: 'γυμνάζομαι',      translation: 'заниматься спортом, упражняться', past: 'γυμνάστηκα', future: 'θα γυμναστώ'   },
  { greek: 'ξεκουράζομαι',    translation: 'отдыхать',               past: 'ξεκουράστηκα',     future: 'θα ξεκουραστώ'     },
  { greek: 'δοκιμάζω',        translation: 'пробовать, примерять',   past: 'δοκίμασα',         future: 'θα δοκιμάσω'       },
  { greek: 'επιμένω',         translation: 'настаивать',             past: 'επέμεινα',          future: 'θα επιμείνω'       },
  { greek: 'υπηρετώ',         translation: 'служить',                past: 'υπηρέτησα',        future: 'θα υπηρετήσω'      },
  { greek: 'ανήκω',           translation: 'принадлежать',           past: 'ανήκα',            future: 'θα ανήκω'          },
  { greek: 'λείπω',           translation: 'отсутствовать, не хватать',past: 'έλειψα',         future: 'θα λείψω'          },
  { greek: 'φιλοξενώ',        translation: 'принимать гостей',       past: 'φιλοξένησα',       future: 'θα φιλοξενήσω'     },
  { greek: 'ευχαριστιέμαι',   translation: 'наслаждаться, получать удовольствие', past: 'ευχαριστήθηκα', future: 'θα ευχαριστηθώ'},
  { greek: 'παραπονιέμαι',    translation: 'жаловаться',             past: 'παραπονέθηκα',     future: 'θα παραπονεθώ'     },
  { greek: 'αναφέρω',         translation: 'упоминать, сообщать',    past: 'ανέφερα',          future: 'θα αναφέρω'        },
  { greek: 'ερευνώ',          translation: 'исследовать',            past: 'ερεύνησα',         future: 'θα ερευνήσω'       },
  { greek: 'διαλέγω',         translation: 'выбирать (синоним επιλέγω)',past: 'διάλεξα',      future: 'θα διαλέξω'        },
  { greek: 'απολύω',          translation: 'увольнять',              past: 'απέλυσα',          future: 'θα απολύσω'        },
  { greek: 'προσλαμβάνω',     translation: 'нанимать на работу',     past: 'προσέλαβα',        future: 'θα προσλάβω'       },
  { greek: 'διορθώνω',        translation: 'исправлять',             past: 'διόρθωσα',         future: 'θα διορθώσω'       },
  { greek: 'συγκρίνω',        translation: 'сравнивать',             past: 'συνέκρινα',        future: 'θα συγκρίνω'       }, // Также σύγκρινα
  { greek: 'παραγγέλνω',      translation: 'заказывать',             past: 'παρήγγειλα',       future: 'θα παραγγείλω'     },
  { greek: 'πληρώνω',         translation: 'платить',                past: 'πλήρωσα',          future: 'θα πληρώσω'        },
  { greek: 'κλέβω',           translation: 'красть, воровать',       past: 'έκλεψα',           future: 'θα κλέψω'          },
  { greek: 'ψεύδομαι',        translation: 'лгать',                  past: 'ψεύστηκα',         future: 'θα ψευστώ'         }, // Реже, чаще λέω ψέματα
  { greek: 'ομολογώ',         translation: 'признавать(ся)',         past: 'ομολόγησα',        future: 'θα ομολογήσω'      },
  { greek: 'κατηγορώ',        translation: 'обвинять',               past: 'κατηγόρησα',       future: 'θα κατηγορήσω'     },
  { greek: 'αμφιβάλλω',       translation: 'сомневаться',            past: 'αμφέβαλα',         future: 'θα αμφιβάλλω'      }, // Также αμφέβαλλα
  { greek: 'εξαρτώμαι',       translation: 'зависеть (от)',          past: 'εξαρτήθηκα',       future: 'θα εξαρτηθώ'       },
  { greek: 'σέβομαι',         translation: 'уважать',                past: 'σεβάστηκα',        future: 'θα σεβαστώ'        },
  { greek: 'θαυμάζομαι',      translation: 'вызывать восхищение (пасс.)', past: 'θαυμάστηκα',  future: 'θα θαυμαστώ'      },
  { greek: 'εγκαταλείπω',     translation: 'покидать, оставлять',    past: 'εγκατέλειψα',      future: 'θα εγκαταλείψω'   },
  { greek: 'αναβάλλω',        translation: 'откладывать',            past: 'ανέβαλα',          future: 'θα αναβάλω'        },
  { greek: 'περιορίζω',       translation: 'ограничивать',           past: 'περιόρισα',        future: 'θα περιορίσω'      },
  { greek: 'εκτιμώ',          translation: 'ценить, оценивать',      past: 'εκτίμησα',         future: 'θα εκτιμήσω'       },
  { greek: 'αξίζω',           translation: 'стоить, заслуживать',     past: 'άξιζα',            future: 'θα αξίζω'          },
  { greek: 'διατηρώ',         translation: 'сохранять, поддерживать',past: 'διατήρησα',        future: 'θα διατηρήσω'      },
  { greek: 'υποστηρίζω',      translation: 'поддерживать',           past: 'υποστήριξα',       future: 'θα υποστηρίξω'     },
  { greek: 'ακολουθώ',        translation: 'следовать',              past: 'ακολούθησα',       future: 'θα ακολουθήσω'     },
  { greek: 'συστήνω',         translation: 'рекомендовать, знакомить',past: 'σύστησα',         future: 'θα συστήσω'        },
  { greek: 'αποτυγχάνω',      translation: 'терпеть неудачу',        past: 'απέτυχα',          future: 'θα αποτύχω'        },
  { greek: 'πετυχαίνω',       translation: 'достигать, преуспевать', past: 'πέτυχα',           future: 'θα πετύχω'         },
  { greek: 'διαχειρίζομαι',   translation: 'управлять, распоряжаться',past: 'διαχειρίστηκα',   future: 'θα διαχειριστώ'   },
  { greek: 'συνεργάζομαι',     translation: 'сотрудничать',           past: 'συνεργάστηκα',     future: 'θα συνεργαστώ'     },
  { greek: 'επικοινωνώ',      translation: 'общаться, связываться',  past: 'επικοινώνησα',     future: 'θα επικοινωνήσω'   },
  { greek: 'εμπιστεύομαι',    translation: 'доверять',               past: 'εμπιστεύτηκα',     future: 'θα εμπιστευτώ'     },
  { greek: 'αμφισβητώ',       translation: 'подвергать сомнению, оспаривать', past: 'αμφισβήτησα', future: 'θα αμφισβητήσω' },
  { greek: 'παρεξηγώ',        translation: 'неправильно понимать',   past: 'παρεξήγησα',       future: 'θα παρεξηγήσω'     },
  { greek: 'ανανεώνω',        translation: 'обновлять',              past: 'ανανέωσα',         future: 'θα ανανεώσω'       },
  { greek: 'βελτιώνω',        translation: 'улучшать',               past: 'βελτίωσα',         future: 'θα βελτιώσω'       },
  { greek: 'χειροτερεύω',     translation: 'ухудшать(ся)',           past: 'χειροτέρεψα',      future: 'θα χειροτερέψω'    },
  { greek: 'αντιγράφω',       translation: 'копировать, списывать',  past: 'αντέγραψα',        future: 'θα αντιγράψω'      },
  { greek: 'ευνοώ',           translation: 'благоприятствовать',     past: 'ευνόησα',          future: 'θα ευνοήσω'        },
  { greek: 'παραδέχομαι',     translation: 'признавать',             past: 'παραδέχτηκα',      future: 'θα παραδεχτώ'      },
  { greek: 'συνδέω',          translation: 'соединять, связывать',   past: 'συνέδεσα',         future: 'θα συνδέσω'        },
  { greek: 'αποσυνδέω',       translation: 'отсоединять',            past: 'αποσυνέδεσα',      future: 'θα αποσυνδέσω'     },
  { greek: 'επενδύω',         translation: 'инвестировать',          past: 'επένδυσα',         future: 'θα επενδύσω'       },
  { greek: 'ρισκάρω',         translation: 'рисковать',              past: 'ρισκάρισα',        future: 'θα ρισκάρω'        },
  { greek: 'καταναλώνω',      translation: 'потреблять',             past: 'κατανάλωσα',       future: 'θα καταναλώσω'     },
  { greek: 'εξοικονομώ',      translation: 'экономить',              past: 'εξοικονόμησα',     future: 'θα εξοικονομήσω'   },
  { greek: 'σπαταλώ',         translation: 'тратить (впустую)',      past: 'σπατάλησα',        future: 'θα σπαταλήσω'      },
];

// Примечание: Некоторые глаголы могут иметь несколько вариантов форм прошедшего или будущего времени,
// или их форма будущего времени может совпадать с формой настоящего времени с частицей θα.
// Также, некоторые глаголы являются депонентными (не имеют действительного залога, но имеют действительное значение).
// В списке приведены наиболее употребительные формы аориста и простого будущего времени.
// Для глаголов типа 'μπορώ', 'θέλω', 'πρέπει', 'ξέρω', 'σημαίνω', 'ανήκω', 'αξίζω'
// будущее время часто образуется как 'θα + форма настоящего времени',
// но также могут существовать и другие формы будущего (например, θα θελήσω, θα μπορέσω).
// Я постарался отметить это в комментариях, где это наиболее релевантно.
// Некоторые глаголы могли повториться в процессе добавления, я постарался их удалить.